/**
 * Deployment smoke test.
 *
 * GitHub Pages serves this repository's root directly, so ./index.html is the file
 * players actually load. It is generated by `npm run build` (source entry: app.html).
 * This test executes that exact artifact and asserts the game boots, catching a
 * missing/partial build before it reaches players.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { JSDOM, VirtualConsole } from "jsdom";

const PUBLISHED = "index.html";

function extractBundle(html: string): string {
  const m = html.match(/<script type="module"[^>]*>([\s\S]*?)<\/script>/);
  if (!m) throw new Error(`no inline module bundle found in ${PUBLISHED}`);
  return m[1];
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

describe("published build (index.html)", () => {
  const html = readFileSync(PUBLISHED, "utf8");

  it("is self-contained: no external script or local stylesheet references", () => {
    expect(html).toContain("MagicTD");
    const externalScript = html.match(/<script[^>]+\bsrc="[^"]*"/i);
    expect(externalScript?.[0] ?? null, "published file must not load an external script").toBeNull();
    const localCss = html.match(/<link[^>]+\bhref="\/(?!\/)[^"]*"/i);
    expect(localCss?.[0] ?? null, "published file must not reference a local stylesheet").toBeNull();
    // the dev-only entry must never be referenced by the published build
    expect(html).not.toContain("/src/main.tsx");
  });

  it("boots the game with the inline bundle", async () => {
    // jsdom never runs type="module" scripts. Browsers execute them deferred, so
    // evaluate the bundle after the document is parsed to match browser behaviour.
    const dom = new JSDOM(html, { runScripts: "outside-only", pretendToBeVisual: true, virtualConsole: new VirtualConsole(), url: "https://seamless45-cpu.github.io/MagicTD-Defense/" });
    const bundle = extractBundle(html);
    dom.window.eval(bundle);

    const root = () => dom.window.document.getElementById("root")!;
    // static splash is removed once the app mounts
    for (let i = 0; i < 100 && dom.window.document.getElementById("boot-splash"); i++) await sleep(100);
    expect(dom.window.document.getElementById("boot-splash"), "boot splash should be removed once React mounts").toBeNull();

    // loading screen -> home
    for (let i = 0; i < 200 && !/Command Center/.test(root().textContent || ""); i++) await sleep(100);
    const text = root().textContent || "";
    expect(text).toContain("Command Center");
    // all three modes and the hero picker ship in the published build
    expect(text).toContain("Battle");
    expect(text).toContain("Endless");
    expect(text).toContain("HERO");
    expect(text).toContain("Nova");

    // the deployed bundle carries this update: the 12-tower arsenal, the run shop,
    // party rally, the tower preview and the awakening ceremony
    const markers = [
      "Battle Shop",
      "FRAGMENT EXCHANGE",
      "Master Volume",
      "Daily Rewards",
      "Thunder God",
      "Dragon's Maw",
      "Sunforge",
      "Missile Battery",
      "Toxic Sprayer",
      "CONGRATULATIONS",
      "BATTLE LINEUP",
    ];
    const missing = markers.filter((m) => !html.includes(m));
    expect(missing, `published bundle is missing: ${missing.join(", ")}`).toHaveLength(0);

    dom.window.close();
  }, 30000);
});
